clang -c -Weverything -Wno-unsafe-buffer-usage -Wno-declaration-after-statement print_polynomial.c  
clang -c -Weverything -Wno-unsafe-buffer-usage -Wno-declaration-after-statement main.c   
clang -c -Weverything -Wno-unsafe-buffer-usage -Wno-declaration-after-statement make_knot.c  
clang -c -Weverything -Wno-unsafe-buffer-usage -Wno-declaration-after-statement initialize_polynomial.c  
clang -c -Weverything -Wno-unsafe-buffer-usage -Wno-declaration-after-statement make_crossing.c      
clang -c -Weverything -Wno-unsafe-buffer-usage -Wno-declaration-after-statement adjust_polynomial_degree.c   
clang -c -Weverything -Wno-unsafe-buffer-usage -Wno-declaration-after-statement kauffman_polynomial.c  
clang -c -Weverything -Wno-unsafe-buffer-usage -Wno-declaration-after-statement make_tangle.c  
clang -c -Weverything -Wno-unsafe-buffer-usage -Wno-declaration-after-statement make_kauffman_summand.c  
clang -c -Weverything -Wno-unsafe-buffer-usage -Wno-declaration-after-statement insert_boundary_point.c  
clang -c -Weverything -Wno-unsafe-buffer-usage -Wno-declaration-after-statement copy_tangle.c  
clang -c -Weverything -Wno-unsafe-buffer-usage -Wno-declaration-after-statement delete_boundary_point.c  
clang -c -Weverything -Wno-unsafe-buffer-usage -Wno-declaration-after-statement copy_kauffman_summand.c   
clang -c -Weverything -Wno-unsafe-buffer-usage -Wno-declaration-after-statement crossing_position.c  
clang -c -Weverything -Wno-unsafe-buffer-usage -Wno-declaration-after-statement pair_strands.c  
clang -c -Weverything -Wno-unsafe-buffer-usage -Wno-declaration-after-statement swap_strand_pairs.c  
clang -c -Weverything -Wno-unsafe-buffer-usage -Wno-declaration-after-statement remove_twist.c 
clang -c -Weverything -Wno-unsafe-buffer-usage -Wno-declaration-after-statement remove_circle.c  
clang -c -Weverything -Wno-unsafe-buffer-usage -Wno-declaration-after-statement add_crossing.c  
clang -c -Weverything -Wno-unsafe-buffer-usage -Wno-declaration-after-statement smooth_crossing.c  
clang -c -Weverything -Wno-unsafe-buffer-usage -Wno-declaration-after-statement tangle_index.c         
clang -c -Weverything -Wno-unsafe-buffer-usage -Wno-declaration-after-statement add_to_kauffman_summand.c  
clang -c -Weverything -Wno-unsafe-buffer-usage -Wno-declaration-after-statement add_to_kauffman_summand_collection.c 
clang -c -Weverything -Wno-unsafe-buffer-usage -Wno-declaration-after-statement jones_polynomial.c
clang -c -Weverything -Wno-unsafe-buffer-usage -Wno-declaration-after-statement safe_calloc.c
clang -c -Weverything -Wno-unsafe-buffer-usage -Wno-declaration-after-statement safe_free.c
clang -c -Weverything -Wno-unsafe-buffer-usage -Wno-declaration-after-statement safe_malloc.c
clang -c -Weverything -Wno-unsafe-buffer-usage -Wno-declaration-after-statement make_stack.c
clang -c -Weverything -Wno-unsafe-buffer-usage -Wno-declaration-after-statement push_stack.c
clang -c -Weverything -Wno-unsafe-buffer-usage -Wno-declaration-after-statement pop_stack.c
clang -c -Weverything -Wno-unsafe-buffer-usage -Wno-declaration-after-statement peek_stack.c
clang -c -Weverything -Wno-unsafe-buffer-usage -Wno-declaration-after-statement is_crossing_consecutive.c

clang print_polynomial.o main.o  make_knot.o initialize_polynomial.o make_crossing.o     adjust_polynomial_degree.o  kauffman_polynomial.o make_tangle.o make_kauffman_summand.o insert_boundary_point.o copy_tangle.o delete_boundary_point.o copy_kauffman_summand.o  crossing_position.o pair_strands.o swap_strand_pairs.o remove_twist.o remove_circle.o add_crossing.o smooth_crossing.o tangle_index.o        add_to_kauffman_summand.o add_to_kauffman_summand_collection.o jones_polynomial.o safe_calloc.o safe_free.o safe_malloc.o make_stack.o push_stack.o pop_stack.o peek_stack.o is_crossing_consecutive.o
